### ISSUE TITLE
Error with 3070's asins (Dogs page)

### ISSUE THREAD

**Issue by 0xExpensive** [Hari-Nagarajan/nvidia-bot#273] opened 2020-11-03 19:17 UTC
Script works with the 3080 and 3090 asins list pinned on the discord channel, the second you use the 3070's list or your own 3070's list you get the dogggos page error (Amazon script)

**Comment by worst-mod-confirmed** [comment] 2020-11-03 19:32
This is an amazon error, we can't stop doggos, but we need to be able to work around them.

**Comment by worst-mod-confirmed** [comment] 2020-11-03 19:36
Duplicate of #266

**Closed by worst-mod-confirmed** 2020-11-03 19:36 UTC
Labels: critical, enhancement
