### ISSUE TITLE
Amazon 

### ISSUE THREAD

**Issue by rawnin** [Hari-Nagarajan/nvidia-bot#274] opened 2020-11-04 18:16 UTC
I have been running the bot without issue for a bit over a week, and it just started crashing consistently. Any recommendations?

`bot@bot-VirtualBox:~/dev/nvidia-bot$ ls
 _Amazon.bat                   app.py            _bbuy-msi.bat  '__INSTALL (RUN FIRST).bat'   notify.mp3            Pipfile        screenshot.png
 amazon_config.json            app.spec          cli             keylinks.md                  nvidia-bot.log        Pipfile.lock   stores
 amazon_config.template_json   _bbuy-fe.bat      config          LICENSE                      _nvidiadotcom.bat     purchase.mp3   utils
 amazon-wait_for_pages.png     _bbuy-gbyte.bat   docs            notifications                nvidia-workflow.png   README.md
bot@bot-VirtualBox:~/dev/nvidia-bot$ pipenv shell
Launching subshell in virtual environment…
 . /home/bot/.local/share/virtualenvs/nvidia-bot-h_48_cFM/bin/activate
bot@bot-VirtualBox:~/dev/nvidia-bot$  . /home/bot/.local/share/virtualenvs/nvidia-bot-h_48_cFM/bin/activate
(nvidia-bot) bot@bot-VirtualBox:~/dev/nvidia-bot$ pipenv install
Installing dependencies from Pipfile.lock (2a6997)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:00
Ignoring pyobjc: markers 'sys_platform == "darwin"' don't match your environment
(nvidia-bot) bot@bot-VirtualBox:~/dev/nvidia-bot$ python app.py amazon
2020-11-04 10:04:46 bot-VirtualBox nvidia-bot[1772] INFO Initializing Apprise handler
2020-11-04 10:04:46 bot-VirtualBox nvidia-bot[1772] INFO Initializing other notification handlers
2020-11-04 10:04:46 bot-VirtualBox nvidia-bot[1772] INFO Enabled Handlers: ['Audio']
2020-11-04 10:04:59 bot-VirtualBox nvidia-bot[1772] INFO Waiting for home page.
2020-11-04 10:05:29 bot-VirtualBox nvidia-bot[1772] INFO Stuck on a captcha... Lets try to solve it.
2020-11-04 10:05:32 bot-VirtualBox nvidia-bot[1772] INFO The solution is: TGNJNF
2020-11-04 10:05:33 bot-VirtualBox nvidia-bot[1772] ERROR No module named 'gi'
2020-11-04 10:05:33 bot-VirtualBox nvidia-bot[1772] WARNING Error playing notification sound. Disabling local audio notifications.
2020-11-04 10:05:45 bot-VirtualBox nvidia-bot[1772] INFO Already logged in
2020-11-04 10:05:45 bot-VirtualBox nvidia-bot[1772] INFO Checking stock for items.
2020-11-04 10:06:16 bot-VirtualBox nvidia-bot[1772] ERROR An error happened, please submit a bug report including a screenshot of the page the selenium browser is on. There may be a file saved at: amazon-wait_for_pages.png
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "/home/bot/.local/share/virtualenvs/nvidia-bot-h_48_cFM/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/bot/.local/share/virtualenvs/nvidia-bot-h_48_cFM/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/bot/.local/share/virtualenvs/nvidia-bot-h_48_cFM/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bot/.local/share/virtualenvs/nvidia-bot-h_48_cFM/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bot/.local/share/virtualenvs/nvidia-bot-h_48_cFM/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/bot/dev/nvidia-bot/cli/cli.py", line 27, in decorator
    func(*args, **kwargs)
  File "/home/bot/dev/nvidia-bot/cli/cli.py", line 81, in amazon
    amzn_obj.run_item(test=test)
  File "/home/bot/dev/nvidia-bot/stores/amazon.py", line 155, in run_item
    while not self.something_in_stock():
  File "/home/bot/dev/nvidia-bot/stores/amazon.py", line 172, in something_in_stock
    self.check_if_captcha(self.wait_for_pages, ADD_TO_CART_TITLES)
  File "/home/bot/dev/nvidia-bot/stores/amazon.py", line 241, in check_if_captcha
    raise e
  File "/home/bot/dev/nvidia-bot/stores/amazon.py", line 222, in check_if_captcha
    func(args)
  File "/home/bot/dev/nvidia-bot/stores/amazon.py", line 245, in wait_for_pages
    selenium_utils.wait_for_any_title(self.driver, page_titles, t)
  File "/home/bot/dev/nvidia-bot/utils/selenium_utils.py", line 93, in wait_for_any_title
    WebDriverWait(d, time).until(AnyEc(*[ec.title_is(title) for title in titles]))
  File "/home/bot/.local/share/virtualenvs/nvidia-bot-h_48_cFM/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:`

![amazon-wait_for_pages](https://user-images.githubusercontent.com/9610634/98152552-c5ec9800-1e86-11eb-9827-6f8a44e9a76f.png)

**Comment by DakkJaniels** [comment] 2020-11-04 18:29
Duplicate of issue #266 and #269

**Closed** 2020-11-05 00:05 UTC
