### ISSUE TITLE
Where can I access the asin_list? Just couldnt figure it out.

### ISSUE THREAD

**Issue by RF-Dante** [Hari-Nagarajan/nvidia-bot#272] opened 2020-11-02 21:10 UTC
I was able to set all things up (amazon_config as well) , executed the command, and the program bought me a flash drive. Maybe it was a test asin_list. I just want to add list of 3080's for Evga FTW3 Ultra, Asus Tuf OC and Asus Rog Strix OC. Can you please help with this? 
Current settings for amazon:
"asin_list": ["B07JH53M4T","B08HR7SV3M"],
"amazon_website": "amazon.com"

**Comment by DakkJaniels** [comment] 2020-11-02 21:20
You have to modify the list with the ASINs you want. B07JH53M4T is a USB stick which is why it bought a USB stick.

**Comment by RF-Dante** [comment] 2020-11-02 21:38
Got it! I never noticed that the ASINs are available in the URL, silly me. :-)

Another noob question, this will only purchase if the item is at MSRP or Sold By: Amazon right? I wouldnt want to end up purchasing from a scalper at a higher price.

**Comment by DakkJaniels** [comment] 2020-11-02 21:40
I believe it should only purchase sold by Amazon - it will not purchase a 3rd party's listing, unless the listing is only for that 3rd party (if it's a duplicate of the main ASIN that is associated only with that 3rd party's listing).

**Comment by RF-Dante** [comment] 2020-11-02 21:53
Thanks!
So far, hopefully none are from 3rd party sellers.
"B08HR3Y5GQ"
"B08HH5WF97"
"B08FC5L3RG"
"B08HR7SV3M"
"B08J6F174Z"

**Closed** 2020-11-03 11:04 UTC
